version: '3.4'

services:
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/phpfpm.Dockerfile
    volumes:
      - ./app:/var/www/html:cached
      - ./docker/phpfpm:/usr/local/etc/php/custom.d
    image: php-fpm
  webserver:
    image: nginx:latest
    links:
      - php-fpm
    volumes:
      - ./app/:/var/www/html
      - ./storage/nginx-logs:/var/log/nginx
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8010:80"

  rabbitmq: # The RabbitMQ container.
    image: rabbitmq:3-management
    ports:
      - 15672:15672


